### ISSUE TITLE
Error : Cannot call value of non -function type 'Error?'

### ISSUE THREAD

**Issue by Tataouine** [artikcloud/tutorial-swift-sdksample#1]
Hello,

I have 2 same error in ViewController.swift 

at line : 
`}.error { error -> Void in` 

Xcode gives me this error : 
"Cannot call value of non -function type 'Error?'"

Thanks you for your help

**Comment by yujingwu** [comment]
@Tataouine  Thanks for reporting this. This is a bug. We are fixing it.

**Comment by jonathanpaek** [comment]
@Tataouine you are using newer SDK for Swift 3 ... however code syntax is for the older SDK Swift2.   

This has been updated.

**Comment by Tataouine** [comment]
Thank you
