### ISSUE TITLE
error: "Please provide a valid authorization header"

### ISSUE THREAD

**Issue by sumesh1993** [artikcloud/tutorial-swift-sdksample#3]
Hi,
 I am not using any artik cloud SDK's.

I am developing a react native app.

when i make a GET call to https://api.artik.cloud/v1.1/users/self
i am getting the subjected error.

in header i am sending the token that i have successfully generated 
ex - Authorization: Bearer my_token

Do i need to send anything else in the request header or as a parameter ?
What am i missing ?

@yujingwu

**Comment by yujingwu** [comment]
@jonathanpaek  please handle this. DX-1513. thanks

**Comment by jonathanpaek** [comment]
@sumesh1993 please send this question form below (if not related to SDK):
https://artik.cloud/contact-us/ — will respond there.

**Comment by sumesh1993** [comment]
request 1146 already open. please revert
